### PR TITLE
Indicate negation status on the context page as well.

### PR DESCRIPTION
**Pull request by ralphbean**

### CODE REVIEW

**Comment by ralphbean** [comment]
Before:

before

And after:

after

**Comment by pypingou** [comment]
Maybe add a title to explain the difference between the two icons when you mouse hover it?

**Comment by ralphbean** [comment]
> Maybe add a title to explain the difference between the two icons when you mouse hover it?

Good idea.  Done in 0d0eeac.

**Comment by ralphbean** [comment]
This one's pretty simple, so I'm going to assume @pypingou's suggestion was a :+1:.  Let me know if that's not the case and I can revert.

**Comment by pypingou** [comment]
It was sorry, I should have mentioned it after 0d0eeac

**Pull request merged**
