### PR TITLE
Add fedmenu to the master template

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by pypingou** [comment]
Again not tested :)

But we should see about improving the README file to explain how to run the app :)

**Comment by ralphbean** [comment]
> But we should see about improving the README file to explain how to run the app :)

It's all in the base FMN readme here:  https://github.com/fedora-infra/fmn/#hacking

And the fmn.web readme links to that:  https://github.com/fedora-infra/fmn.web/#hacking

Can you try those and test it?

**Comment by pypingou** [comment]
>    It's all in the base FMN readme here:
>    https://github.com/fedora-infra/fmn/#hacking

I had seen it but had missed:
``
$ pushd fmn.web; python fmn/web/main.py; popd
``
I'll run it,

Thanks

**Comment by pypingou** [comment]
Seems to work fine

**Comment by ralphbean** [comment]
FMN has users.  Can we use the ``'user'`` feature of fedmenu for their profile?

**Comment by ralphbean** [comment]
Awesome!  :+1:!

**Pull request merged**
